exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

# Site settings
title: Nils Deppe
email: nilsdeppe@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I hope to share my excitement and knowledge of physics, C++, metaprogramming,
  high performance computing, and scientific computing here.
title_fontsize: 2
url: "https://nilsdeppe.com"
# TODO: add research gate?
cv: "assets/pdfs/cv.pdf"
orcid_id: 0000-0003-4557-4115
arxiv: https://arxiv.org/search/?query=Deppe%2C+Nils&searchtype=author&abstracts=show&order=-announced_date_first&size=200
github_username:  nilsdeppe
bitbucket_username: ndeppe
linkedin_username: nilsdeppe
inspirehep_id: 1794662
# Getting 2x icon size to center required editing airspace.css to have:
#
# Need to adjust spacing also depending on title size. 8px seems to be okay
#
# header .navbar-default .navbar-icons {
#   padding-top: 8px;
# }
icon_size: 2x
footer_icon_size: 1x

# Set this value to "" if you want your site to be root
baseurl: ""
cover: "/assets/cover.png"

# Build settings
markdown: kramdown
highlighter: rouge

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."
